export const ACTIONS = {
  GET_CONTACT: "GET_CONTACT", // запрос
  GET_CONTACT_SUCCESS: "GET_CONTACT_SUCCESS", // если нет ошибок - сохранить данные в store
  GET_CONTACT_FAIL: "GET_CONTACT_FAIL",
  ADD_CONTACT: "ADD_CONTACT",
  EDIT_CONTACT: "EDIT_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  SET_USER: "SET_USER",
  CLEAR_USER: "CLEAR_USER",
  SET_CONNECTION_IN_PROGRESS_STATE: "SET_CONNECTION_IN_PROGRESS_STATE",

  SHOW_CONTACT_LIST: "SHOW_CONTACT_LIST",
  SET_CONTACTS: "SET_CONTACTS",
};
