export const ACTIONS = {
  GET_CONTACT: "GET_CONTACT",
  GET_CONTACT_SUCCESS: "GET_CONTACT_SUCCESS",
  GET_CONTACT_FAIL: "GET_CONTACT_FAIL",
  ADD_CONTACT: "ADD_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  UPDATE_CONTACT: "UPDATE_CONTACT",
  CLEAR_CONTACT: "CLEAR_CONTACT",
  SET_USER: "SET_USER",
  CLEAR_USER: "CLEAR_USER",
  SET_CONNECTION_IN_PROGRESS_STATE: "SET_CONNECTION_IN_PROGRESS_STATE",
};
